### ISSUE TITLE
buildQueue creates entry for hidden/non-existing localised pages

### ISSUE THREAD

**Issue by brotkrueml** [tomasnorre/crawler#584]
## Bug Report

**Current Behavior**
Given is a single-tree multi-lingual project with en als default language and de, pl and tr as other languages. Now create a configuration record with "pidsonly" for a page where only en and de exists as available pages, pl is hidden and tr is not existing. When calling crawler:buildQueue for this configuration four entries are created into the queue table, one for each of the four languages.

This also happens for the default language, when "Hide default language" is activated in the page properties.

As invalid pages are added to the page the processQueue exits with an error when processing a non-existing page.

**Expected behavior/output**
Only rows for the available translated pages should be created in the queue table.

**Environment**
- Crawler version: 9.0.1
- TYPO3 version: 10.4.3
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by tomasnorre** [comment]
Hi @brotkrueml 

I understand the problem here and it's a bug in the crawler, unknown till now. 
Do you agree with me, that it's not "critical" as the existing pages will still be crawler as they should be? 

Please comment on this so that I know if I assigned the correct priority to this bug.

**Comment by brotkrueml** [comment]
I want to use the extension as cache warmup. Every page that does not exist means, the process command exits with an error and the next run of the process command (when the given grace time is over) will crawl some other pages till the next error. And there are plenty of pages which are not translated in this specific project.

**Comment by tomasnorre** [comment]
Then it's a higher priority than I saw this. I'll change the label to have it addressed earlier. 
Didn't expect the process to stop, with the 9.0.0 version, it started handling 404 and 50x better, but sounds like there still is a problem.

**Comment by tomasnorre** [comment]
I've tried to reproduce this, but on a 9LTS, which I cannot. You can see that all three languages (default, da, de) are added to the queue, and no errors by processing. 

![Screenshot from 2020-06-03 17:19:11](https://user-images.githubusercontent.com/1212481/83655352-9deac700-a5be-11ea-90b1-cc3339b008da.png)
![Screenshot from 2020-06-03 17:19:33](https://user-images.githubusercontent.com/1212481/83655355-9e835d80-a5be-11ea-80c6-dbc3f513b122.png)

I'll try to update my devbox to 10 LTS to see if it makes any difference to me. 

FYI: I totally agree with you that they should be added to the queue in the first place, just want to figure out why it gives you problems first.

**Comment by tomasnorre** [comment]
I cannot reproduce the problem with the `processQueue` on 10 LTS either. And I even have problem errors in the crawler log.

Do you have anything special in your setup that I might not think of testing/configuring? 

![Screenshot from 2020-06-03 17:54:10](https://user-images.githubusercontent.com/1212481/83659007-4864e900-a5c3-11ea-93e0-e3be706463de.png)
![Screenshot from 2020-06-03 17:54:19](https://user-images.githubusercontent.com/1212481/83659010-48fd7f80-a5c3-11ea-86f1-fbe520da96ee.png)

**Comment by tomasnorre** [comment]
This is the site configuration I use for the crawler devbox

```yaml
base: 'https://crawler-devbox.ddev.site/'
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: Default
    enabled: true
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: ab
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: global
    languageId: '0'
  -
    title: Dansk
    enabled: true
    base: /da/
    typo3Language: default
    locale: da_DK.UTF-8
    iso-639-1: da
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: dk
    languageId: '1'
  -
    title: German
    enabled: true
    base: /de/
    typo3Language: default
    locale: de_de.UTF-8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: '2'
rootPageId: 1
```
