### ISSUE TITLE
Site config baseVariants are not considered

### ISSUE THREAD

**Issue by Patta** [tomasnorre/crawler#851]
## Bug Report

**Current Behavior**
The `base_url` field in the configuration record shows the following info text: "Leave empty for fetching the base URL from the Site Configuration."
My site config has configured `baseVariants` for "Production/Staging" and "Development" environment.
For example, if i run the following cli command `vendor/bin/typo3 crawler:buildQueue 1 site-public,site-usergroup1,site-usergroup2 --depth 9 --mode exec` in my staging environment, it still takes the base url instead of the staging base url from the baseVariants of the site config. Current workaround, add additional crawler config for staging environment.

**Expected behavior/output**
Crawler configuration with empty base_url field can be used in a staging environment, which has configured baseVariants in site config.

**Steps to reproduce**
* staging instance with configured site base for staging in site config baseVariants
* add crawler config (via backend) to root page without any field filled except the name "site-public"
* run in staging cli: `vendor/bin/typo3 crawler:buildQueue 1 site-public --depth 9 --mode exec`

Crawler outputs error for each page `Composer Error checking Crawler Result:  "503 Service Unavailable"...`

**Environment**
- Crawler version(s): 11.0.1
- TYPO3 version(s): 10.4.21
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by tomasnorre** [comment]
Thanks for reporting. 

I'll be looking into this.

**Comment by tomasnorre** [comment]
I have stumbled upon this before, but I thought it was a mistake in my test setup. I should have believed my tests more. 

I'll try to add tests for this, and fix it, to ensure that it doesn't break again.

**Comment by tomasnorre** [comment]
I cannot reproduce this problem with the Crawler Devbox. 

I have following config: 

```yaml
base: /
baseVariants:
  -
    base: applicationContext.acme.com
    condition: 'applicationContext == "Production"'
```

If I set my applicationContext to Production it gets the expected BaseURL in the CrawlerQueue. 

I do have a problem with crawling with baseURL set to `/` though. But this sounds like a different issue, which was the one I was refering to here. 

> I have stumbled upon this before, but I thought it was a mistake in my test setup. I should have believed my tests more.

I'll keep looking into this.

**Comment by Patta** [comment]
Thanks for your feedback. I set the applicationContext via htaccess, maybe the context is not available in the cli?

htaccess excerpt:
```
<IfModule mod_rewrite.c>

    # Rules to set ApplicationContext based on hostname
    RewriteCond %{HTTP_HOST} ^(.*)\.my\-site\.localhost$
    RewriteRule .? - [E=TYPO3_CONTEXT:Development]
    RewriteCond %{HTTP_HOST} ^(.*)\.mysite\.info$
    RewriteRule .? - [E=TYPO3_CONTEXT:Production/Staging]
    RewriteCond %{HTTP_HOST} ^(.*)\.my\-site\.info$
    RewriteRule .? - [E=TYPO3_CONTEXT:Production]
</IfModule>
```
site config excerpt:
```
base: 'https://www.my-site.info/'
baseVariants:
    -
        base: 'https://www.my-site.localhost/'
        condition: 'applicationContext == "Development"'
    -
        base: 'https://stage-www.mysite.info/'
        condition: 'applicationContext == "Production/Staging"'
```
